[workspace]
members = [
    "peregrine",
    "potato_sat",
    "peregrine_macros",
    "serde_closure"
]
exclude = [
    "perf",
    "perf/perf_macros"
]
default-members = [
    "peregrine", "potato_sat"
]

resolver = "2"

[profile.release]
debug = true
