[workspace]
members = [
    "peregrine",
    "peregrine_macros",
    "potato_sat",
    "serde_closure",
    "aerie_lander",
]
exclude = [
    "perf",
    "perf/perf_macros"
]
default-members = [
    "peregrine", "potato_sat", "aerie_lander"
]

resolver = "2"

[profile.release]
debug = true
