[package]
name = "peregrine"
version = "0.2.0"
edition = "2024"

authors = ["Joel Courtney <joel.e.courtney@gmail.com>"]
description = "A discrete event simulation engine similar to NASA-AMMOS's Aerie-Merlin."
readme = "README.md"
repository = "https://github.com/JoelCourtney/peregrine"
license = "MIT OR Apache-2.0"
keywords = ["simulation"]
categories = ["aerospace::simulation", "simulation"]

[features]

[dependencies]
forte = "1.0.0-alpha.4"
parking_lot = { version = "0.12", features = ["send_guard"] }
async-lock = "3.4"
peregrine_macros = { path = "peregrine_macros" }
futures = { version = "0.3.31", default-features = false, features = ["std"] }
oneshot = "0.1.11"
replace_with = "0.1.8"
slotmap = "1.0.7"

[dev-dependencies]

[workspace]
members = [".", "peregrine_macros"]
