[package]
name = "perf"
version = "0.1.0"
edition = "2024"

[features]
nightly = ["peregrine/nightly"]

[dependencies]
peregrine = { path = "../peregrine", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive"] }
typetag = "0.2.20"
