[package]
name = "perf"
version = "0.1.0"
edition = "2021"

[features]
nightly = ["peregrine/nightly"]

[dependencies]
peregrine = { path = "../peregrine" }
serde = { version = "1.0.218", features = ["derive"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
